### ISSUE TITLE
Member Registration: Password too Common Issue

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#116]
The password rules are good, however, we need to add a bubble, hint or text under the password with the rules.  Its very aggravating to try and try to get the password correct.  
![image](https://user-images.githubusercontent.com/26025574/96684243-95333b80-137b-11eb-923e-4474a7a00567.png)

**Comment by heldyboy** [comment]
Planned date for completion is June 10th, 2021

**Comment by heldyboy** [comment]
Peter will look into this.  Link for the document is below. 

https://drive.google.com/file/d/1vq9SWGHfevERDLflo4hDGJSRQDJakxQ7/view?usp=sharing

**Comment by peterbogdan** [comment]
@heldyboy 
Let me know what message you want here
![image](https://user-images.githubusercontent.com/26739094/121579812-bfce2380-ca34-11eb-915d-314c2e7fb24b.png)

**Comment by peterbogdan** [comment]
updated:
![image](https://user-images.githubusercontent.com/26739094/122786566-1c470380-d2bd-11eb-9661-53c24ca6322e.png)

**Comment by peterbogdan** [comment]
We updated the settings for password_validators as follows:
```Passwords must contain at least:
8 characters
1 numeric digit
1 special character```
