### ISSUE TITLE
[ Page not found ] https://asrg.io/ > Become a member

### ISSUE THREAD

**Issue by alanamircruz** [ASRG/asrg.io#130]
1. https://asrg.io/

2. Click on right-top menu > Become a member
![image](https://user-images.githubusercontent.com/14240398/98453797-6e3b7e80-215d-11eb-919b-1d7456934d3c.png)

3. Page not found
![image](https://user-images.githubusercontent.com/14240398/98453804-8d3a1080-215d-11eb-962b-09809c48c647.png)

**Comment by brandonbarry123** [comment]
non-issue: legacy.
