### ISSUE TITLE
Change database password

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#132]
Change the password for the DB.

* .env file for deploy
  * It can be changed in the docker compose if it is a new database. Once the db is created the change must be done manually not pushed on git.
* Change DB password through SQL in deployment. **Ommited** as no manual steps will be done on server.

HINT:
- *[Using .env file](https://medium.com/analytics-vidhya/getting-started-with-postgresql-using-docker-compose-34d6b808c47c)
- https://www.enterprisedb.com/postgres-tutorials/how-connect-postgresql-using-sql-developer-visual-studio-and-dbeaver
- https://www.postgresqltutorial.com/postgresql-change-password/

**Comment by alanamircruz** [comment]
Already set through .env file in docker-compose.yml, closing.

``` yaml
env_file: ./some/path/.env
```
