### ISSUE TITLE
Domain Forwarding

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#14]
Need to get domain forwarding (CMAKE) for docs.asrg.io and admin.asrg.io working.  They should be pointing to gitbooks.

**Comment by heldyboy** [comment]
Update... after speaking with teh support group for a week at Dreamhost, finally got the Gitbooks connection working.  However there still seems to be a problem.  CMAKE is correctly setup at Dreamhost, and the connect to Gitbooks seems to be working (at least they recognize the connection is there), but the website still won't load.  Need to investigate more.

**Comment by chrsengel** [comment]
#34 guess this is related again haha

**Comment by heldyboy** [comment]
Interesting... I'm working on it right now.

**Comment by chrsengel** [comment]
admin.asrg.io is still not working.

**Comment by heldyboy** [comment]
I don't think it's going to work... 
<img width="788" alt="Screen Shot 2019-12-24 at 12 46 17" src="https://user-images.githubusercontent.com/26025574/71411879-6c52f480-264b-11ea-98b3-b2592fc89214.png">
