### ISSUE TITLE
Projects Page Authenticated

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#140]
![image](https://user-images.githubusercontent.com/26025574/99935436-fb3b2600-2d60-11eb-8a7b-88d339c741be.png)

**Comment by heldyboy** [comment]
The pictures are not loading. Can you please get the pictures to load?

**Comment by antoniumolnar** [comment]
done

**Comment by brandonbarry123** [comment]
@heldyboy Apparently, this is fixed. It's not clear why or what fixed it, but it's working now. Can you take a look and make sure? https://asrg.io/projects

**Comment by brandonbarry123** [comment]
@peterbogdan The images have disappeared again. WTF?
