### ISSUE TITLE
Registration Page:  All fields should be requried

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#141]
Please change so that all fields will be required.

![image](https://user-images.githubusercontent.com/26025574/99935724-ab109380-2d61-11eb-80e5-95cb06f9dbfc.png)

**Comment by heldyboy** [comment]
Right now, you can register with out giving a first and last name. Please make sure that all fields are filled in.

**Comment by antoniumolnar** [comment]
I try to register a new user, all fields are required only on locations a new user can let "I don't know"

**Comment by antoniumolnar** [comment]
![First Name](https://user-images.githubusercontent.com/65129905/99993088-dcb84780-2dbf-11eb-998c-928406dc071f.png)

**Comment by antoniumolnar** [comment]
![Last Name](https://user-images.githubusercontent.com/65129905/99993097-e0e46500-2dbf-11eb-880a-903dd1231420.png)

**Comment by heldyboy** [comment]
Ok. We found users in the database with out first and last names. I deleted them. But if it's required, maybe they were from a previous version or db

**Comment by brandonbarry123** [comment]
@heldyboy Going to close. Probably the users (me) were created via the command line (creating an admin account), which would not store a first/last name.
