### ISSUE TITLE
Profile Update: Server Error 500

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#153]
After updating the profile, and clicking submit or update profile, user experiences a "Se
![server](https://user-images.githubusercontent.com/26025574/101279840-6fe07c80-37c5-11eb-966d-f4c071aba1b5.png)
rver Error (500)"

**Comment by brandonbarry123** [comment]
Still receiving this error. @peterbogdan, did you change something here?

It appears that a int() is being run on a "QuerySet":

In /opt/code/authentication/views.py in account_edit_view

`user_obj.user_permissions.add(perms) `

Perms is a QuerySet, where "user_permissions.add runs int() on it. 


Request Method: | POST
-- | --
http://localhost:8080/edit-profile/
2.1.15
TypeError
int() argument must be a string, a bytes-like object or a number, not 'QuerySet'
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py in get_prep_value, line 965
/usr/local/bin/python
3.6.10
['/opt/code',  '/usr/local/bin',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
Wed, 30 Dec 2020 18:15:20 +0000
