### ISSUE TITLE
Nginx, File upload Limit (Need to either increase or document the limit)

### ISSUE THREAD

**Issue by Melvin-Thomas-Dev** [ASRG/asrg.io#165]

**Comment by Melvin-Thomas-Dev** [comment]
The file size limit has been set to 3MB.

**Comment by Melvin-Thomas-Dev** [comment]
There seems to be some problem with the Nginx file. the upload limit is not set. The present limit is 1MB which is the default for Nginx

**Comment by brandonbarry123** [comment]
@peterbogdan do you have any idea why nginx might not be accepting the increase in size? 

@Melvin-Thomas-Dev tried updating the file "asrg.template" with a new field "client_max_body_size". I believe it would belond in "server" > "location ^~ /media/ "


# asrg.conf
access_log /var/log/nginx/nginx.http.log;
error_log /var/log/nginx/nginx.http.error.log;
upstream asrg {
        server asrg-app:${ASRG_APP_PORT};
}
server {
    listen ${NGINX_HTTP_PORT};
    listen [::]:${NGINX_HTTP_PORT};
    server_name ${SERVER_NAME};
    return 302 ${DOLLAR}scheme://${DOLLAR}server_name${DOLLAR}request_uri;
}
server {
    # Uncomment these to use https
    # listen ${NGINX_HTTPS_PORT} ssl http2;
    # listen [::]:${NGINX_HTTPS_PORT} ssl http2;
    # server_name ${SERVER_NAME};
    # ssl_certificate    /etc/nginx/certs/asrg.crt;
    # ssl_certificate_key    /etc/nginx/certs/asrg.key;
    # Logs.
    access_log /var/log/nginx/nginx.vhost.access.log;
    error_log /var/log/nginx/nginx.vhost.error.log;
    # Site configuration.

    location / {
        proxy_pass http://asrg;
        proxy_set_header Host ${DOLLAR}http_host;
        proxy_set_header X-Real-IP ${DOLLAR}remote_addr;
        proxy_set_header X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto ${DOLLAR}scheme;
    }

    location ^~ /media/ {
        autoindex on;    
        alias /opt/asrg/media/;    
        expires 30d;
    }
}
