### ISSUE TITLE
Reorganize/clean up /admin.

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#166]
- [x] Rename "Chapters" to "Locations", move to "Locations" category and delete redundant "Locations".
- [ ] Rename "Authentication" to "User Management" to contain "Users" and "User Profiles"
- [x] Split out "website" into dedicated apps.

**Comment by peterbogdan** [comment]
Chapters will be renamed to Locations in the Authentication tab.
I will remove the Locations model as it is not used.
