### ISSUE TITLE
I recommend to add a kind of CMS (at least for the Vulnerability Management area)

### ISSUE THREAD

**Issue by SvenSchran** [ASRG/asrg.io#167]
- CMS means Content Management System
- I like to update the content of the page (where it is planned to provide a process description for the Vulnerability Disclosure Program)
- but I don't like to take care about HTML, JavaScript or similar coding

**Comment by brandonbarry123** [comment]
For now, we will manually update html as needed. @SvenSchran you can just create a card here to get content updated via HTML so you don't need to.
