### ISSUE TITLE
User email validation: We need to ensure that an account is not registered until they confirm through email.

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#169]
- [x] Alan to set up GMAIL as SMTP
- [x] Peter to decide on library to use and integrate. 
- [x] Implement.
- [x] Peter to test.

The flow should follow this diagram:

https://lucid.app/lucidchart/invitations/accept/1741d9cc-6395-407e-b0e6-3c0859647a5e

We can achieve the above with the one of the following:

https://pypi.org/project/Django-Verify-Email/

https://pypi.org/project/Django-Verify-Email/

**Comment by brandonbarry123** [comment]
@peterbogdan 

Can we replicate something similar to this with an ASRG logo for the email template?

![Screenshot_3](https://user-images.githubusercontent.com/18297844/105633137-ed6b5500-5e24-11eb-9c5b-521121825cca.png)

**Comment by brandonbarry123** [comment]
[test.html.zip](https://github.com/ASRG/asrg.io/files/5862413/test.html.zip)


@peterbogdan here is the html for the above if it's helpful to start w/ that as a template.

**Comment by peterbogdan** [comment]
Will try to use this @brandonbarry123 ,
some questions regarding this

- If you want to put some instagram/facebook/twitter accounts to the icons, if not I will just remove them.
- same for terms of use/Contact us, couldn't find a page for these.

**Comment by peterbogdan** [comment]
![image](https://user-images.githubusercontent.com/26739094/105918444-99d35400-603c-11eb-90db-3ade59fd766b.png)
@brandonbarry123 what do you think?
just let me know what you want me to do with the address and ping me for some of the links
