### ISSUE TITLE
If an Admin set the Event state to Invited the event is not shown anymore in the Events list

### ISSUE THREAD

**Issue by SvenSchran** [ASRG/asrg.io#194]
If the event **state** is set to _Invited_ the event is not shown anymore in the public available list.

Review comments for proper event state behavior.

**Comment by heldyboy** [comment]
The behavior of the listed events needs to be changed.  If the event is "invited" or "confirmed" then the Event should be shown in the list.

**Comment by brandonbarry123** [comment]
Why would we show events publicly in the “invited” state?

Or, are you saying that “invited” events are shown and shouldn’t be?

BB

**Comment by brandonbarry123** [comment]
The expected behavior for this field is the following:

In-plan - not public.
Confirmed - public. 
Invited - public. (Future use: sends out information to be posted.)
Completed - public, state is set automatically if current time is past "End date" (appears in "past events")
Cancelled - not public.

**Comment by peterbogdan** [comment]
Fixed the issue and now all confirmed and invited events are shown.
