### ISSUE TITLE
ASIP Dashboard: embed dashboard under "Threat Intelligence" tab via an iframe.

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#198]
- [x] Stand up local ELK stack
- [x] Create a example dashboard.
- [x] iframe dashboard url into Threat Intelligence tab in member portal.

The idea: we'll change iframe dashboard URL once we get in production.

**Comment by heldyboy** [comment]
@brandonbarry123 , I was discussing this with Falk the other day and he mentioned that maybe Kibana or some other freeware type tool could be used.  Maybe this would be a better option then running a full scale Splunk machine. (And might save some money).

**Comment by peterbogdan** [comment]
![image](https://user-images.githubusercontent.com/26739094/111072553-c1468900-84e3-11eb-8845-d2817a7271be.png)
@brandonbarry123 @heldyboy  Integrating an iframe from Kibana works nice locally
Let me know if there are any specific things you want me to test

**Comment by peterbogdan** [comment]
TODO 

- [ ] Make the URL for the dashboard a settings that can be put in .env

**Comment by heldyboy** [comment]
We should look into exporting the PNG or exporting the CSV and recreating the graphs in CoreUI. @peterbogdan 

https://www.elastic.co/guide/en/kibana/current/reporting-getting-started.html
