### ISSUE TITLE
Need to be able to post sponsors to public page, via a new app that allows us to upload a "sponsor" to admin page.

### ISSUE THREAD

**Issue by peterbogdan** [ASRG/asrg.io#203]
-  [ ]  Add menu item on the main landing_page for "Become a Sponsor"
-  [ ]  John to provide additional content that will be used on this page
-  [ ]  Create a "sponsors" app with "company" -> logo, company name, company description 
-  [ ]  Have a "space" on the page where current sponsors are shown (from the "company" model above).

**Comment by peterbogdan** [comment]
Add sponsors as a plugin where it can return a specific sponsor as a card (logo + name + description)

**Comment by heldyboy** [comment]
Please add the following fields for the Sponsors in the data model.
- Sponsor Name:
- Website: [url]
- Address:
- Description: [Text]
- General Email Address:
- Start Date: [Date]
- Status: Active, Not Active
- Logo: [image]

**Comment by peterbogdan** [comment]
@heldyboy  Do you want start date to be autocompleted when you add a new entry?

**Comment by peterbogdan** [comment]
![image](https://user-images.githubusercontent.com/26739094/111066021-92211f00-84c5-11eb-93b2-8f36607724d0.png)

Hi @brandonbarry123 @heldyboy I have centered the cards and gave a max-width to the images, let me know if it is ok like this

**Comment by peterbogdan** [comment]
E-mail: hello@asrg.io
