### ISSUE TITLE
As a user, I should be able to click "forgot password" at /login, and reset my password through a link sent to my email.

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#206]

**Comment by peterbogdan** [comment]
![image](https://user-images.githubusercontent.com/26739094/111067280-39a15000-84cc-11eb-9d19-7adca6f6aeb0.png)
Password reset template used for E-mail

**Comment by peterbogdan** [comment]
- [ ] Change template for reset password with the one used at login
