### ISSUE TITLE
Events: Menu Behavior 

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#207]
Hi John,

I just noticed that when I'm on the site for a specific event on our website (e.g. https://asrg.io/events/68) and then click the menu button in the top right corner, "#menu" is added to the url in the end, but the menu is not opened. Tried it for a couple of events and seems to be a persistent issue. Also tried it with Firefox and Edge and same behaviour in both browsers.

--
Best regards,
Jana Karina von Wedel

Automotive Security Research Group (ASRG)
Munich

**Comment by peterbogdan** [comment]
Could not reproduce the issue. I think it was fixed. if not reopen with more info.
