### ISSUE TITLE
Training App

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#227]
We need to create an django app to:
1. Display a directory for Automotive Security Trainings
2. Search function for the Trainings
3. Add a Training to the database.

This should be based on the information in this link: 
https://docs.google.com/spreadsheets/d/1RbH42WqYuzA6rqz4gC2l4Zagv1uhuHHF5egqFVXlmbM/edit?usp=sharing

**Comment by peterbogdan** [comment]
Get all the data from the excel as a model for Training app
Get a datatable as the main view for this (only for authenticated users)
Add a logo image field  to the model
Search function if possible
Filter function
button at the top -> "Add a training" (go to a form to add another training to the list)

**Comment by heldyboy** [comment]
The app is created and in production, however not linked to the main menu. The add function is still not complete. Should be possible until 25.04.2021.

**Comment by peterbogdan** [comment]
Add new status to Training model: Submitted, Released, Expired
Transition to Cards (Use coreUI stuff)

**Comment by heldyboy** [comment]
https://www.figma.com/file/ObpKrLhJ3PSAONOhtipyrp/Untitled?node-id=0%3A1

**Comment by heldyboy** [comment]
The migration of the description is not working correctly.  Decision is to push all the migrated data to the DB in production and then update the descriptions manually afterwards.

**Comment by heldyboy** [comment]
Peter is still working on this.

**Comment by peterbogdan** [comment]
Finished working on the Styling for the sponsors page and addinng the data from google drive 
will push to prod today/tommorrow

**Comment by peterbogdan** [comment]
The description needs to be added manually for trainings.
