### ISSUE TITLE
Join the Community Button

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#23]
The join the community button should check the location of the connection and then forward the person the correct ASRG meetup link.

Stuttgart (ASRG-S): https://www.meetup.com/Automotive-Security-Research-Group-Stuttgart/
Detroit (ASRG-D): https://www.meetup.com/Automotive-Security-Research-Group-Detroit/
Tel Aviv (ASRG-TLV): https://www.meetup.com/Automotive-Security-Research-Group-Tel-Aviv-ASRG-TLV/
Cluj (ASRG-C): https://www.meetup.com/Automotive-Security-Research-Group-Cluj-ASRG-C/
ASRG-SIN

**Comment by chrsengel** [comment]
Implemented with #25 
Has to be tested by members.
