### ISSUE TITLE
User problem with login

### ISSUE THREAD

**Issue by SvenSchran** [ASRG/asrg.io#265]
One user gave the following problem information:

_I registered in your website but I think there is a problem for logging in your portal,although I verified my email address. Is it possible to control it? thank you._

LinkedIn profile of the user: https://www.linkedin.com/in/soheil-nazem-2666a953/

**Comment by heldyboy** [comment]
I also had a problem today with the email registration.  Please take a look what is going wrong.

**Comment by heldyboy** [comment]
Just tested and seems to work.  @SvenSchran can you try as well.

**Comment by heldyboy** [comment]
Unable to replicate issue.

**Comment by heldyboy** [comment]
![image (1)](https://user-images.githubusercontent.com/26025574/118023395-cb5afb80-b35d-11eb-8062-df1cc2850f2b.png)
