### ISSUE TITLE
Need to update the symbols on the website to match the presentation

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#27]

**Comment by heldyboy** [comment]
Can you please update the symbols on the page to match the presentation?  Here is the link to the presentation symbols... 
https://drive.google.com/drive/folders/1FdGTq95NqBa-l08yXSX6k4ZOYXk6OUcx

**Comment by heldyboy** [comment]
Completed.

**Comment by chrsengel** [comment]
You didn't add the images to the `images` folder.

**Comment by chrsengel** [comment]
Nevermind.
