### ISSUE TITLE
different sizes on menu items when I am on the Projects page

### ISSUE THREAD

**Issue by SvenSchran** [ASRG/asrg.io#272]
The size of the menu items for all pages is like the following picture shows:
![grafik](https://user-images.githubusercontent.com/75367305/115931757-ff907a00-a48b-11eb-8596-4d23ec68db81.png)

If I am on the p-Projects page it differs in the following manner:
![grafik](https://user-images.githubusercontent.com/75367305/115931816-1df67580-a48c-11eb-8853-06a7025be9ca.png)

**Comment by heldyboy** [comment]
Fixed.
