### ISSUE TITLE
Add Submit a Vulnerability Page

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#28]
We need a way to submit vulnerabilities. We should have a form which allows for the submission of vulnerabilities anonymously.  I think a form and email address should be possible. We should take a template from already existing vulnerability submission pages... 
https://www.bmwgroup.com/en/general/Security.html
https://hackerone.com/gm

I like BMW... simple and easy.

**Comment by chrsengel** [comment]
I'll have a look. I think we can do this in parallel with the proposed [security.txt](https://securitytxt.org/) standard for websites. We should setup an email (i.e. security@asrg.io) and a PGP keypair.

**Comment by heldyboy** [comment]
Just read security.txt... looks great.  We should reference that as well.  

Security@asrg.io is setup.

**Comment by chrsengel** [comment]
Do you want to setup and securely store the gpg key? I usually use ECC these days.

```bash
gpg --full-gen-key --expert

> 9 (ECC and ECC)
> 1 (Curve 25519)
> 0 - or whatever you want. We can change the expiration later
> Name, etc.
```
We should put the fingerprint into the asrg twitter bio and setup a [keybase](https://keybase.io/) account as well.

To get the fingerprint:

```bash
gpg --fingerprint security@asrg.io > fingerprint.txt
```
To get the public key:

```bash
gpg --armor --export security@asrg.io > security-asrg.asc
```

If needed we can then set up some subkeys for specific asrg members to be able to sign stuff.

**Comment by chrsengel** [comment]
I added the page. @heldyboy  Just add the public key in the `<code>`  tag.

**Comment by chrsengel** [comment]
The site is [live now](https://asrg.io/security.html) alrady because the action uploaded it.

**Comment by heldyboy** [comment]
Done.
