### ISSUE TITLE
New Menu Structure

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#281]
Dashboard
----
#Organization
- Locations
- Member Benefits
#Events
- ASRG
- External
Knowledge
- Awareness
- Library
- Resources
- Training
- Supplier Directory (future)
- Wiki
- Tools
Networking
Collaboration
- Getting Involved
- Intelligence Platform
- Member Portal
- Vulnerability Mgmt.
Academia
- Learning
- Technical Committees
- Student Organizations
- Research
Career 
- Career Resources
- Job Posting

All menu options that are not available, we just grey out.

**Comment by peterbogdan** [comment]
TODO:
Change the text color from white -> look at the old color
Use CoreUI classes for the text from Dashboard 
gray out all the links we don't use ATM

**Comment by heldyboy** [comment]
Please also reduce the font size to look like the CoreUI Demo.
