### ISSUE TITLE
Need to add Language to Training DB

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#296]
Please add a language field to the training app, so that people can add which languages the training is possible.  This should be a multi selectable field (a training might be available in more then one language).

**Comment by peterbogdan** [comment]
Added language choice field with the options from here:
https://github.com/umpirsky/language-list/blob/master/data/en_US/language.json

**Comment by peterbogdan** [comment]
@peterbogdan  TODO: Fix the add new training template, the form is not visible
