### ISSUE TITLE
Event Menu Content

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#299]
Please setup the menu content to have the same page format for all the different links under events with the following filters. 

**For ASRG Meetings filter settings:** 
Location !=ASRG-WORLD
Status == Confirmed or Invited
Event Type == Webinar, Event, or Workshop, 
Mode == Internal

**For ASRG Webinars filter settings:** 
Location == ASRG-WORLD
Status == Confirmed or Invited
Event Type == Webinar, Event, or Workshop, 
Mode == Internal

**For Conferences filter settings:** 
Status == Confirmed or Invited
Event Type == Conference

**For CTF filter settings:** 
Status == Confirmed or Invited
Event Type == CTF

**For Workshops filter settings:** 
Status == Confirmed or Invited
Event Type == Workshop

**Comment by heldyboy** [comment]
Plan completion date is June 10th, 2021

**Comment by peterbogdan** [comment]
@heldyboy there is no Type called "Event"

**Comment by heldyboy** [comment]
@peterbogdan Event = Meeting

**Comment by peterbogdan** [comment]
Will complete this by 23/06
