### ISSUE TITLE
Setup Github actions for automatic deployments

### ISSUE THREAD

**Issue by chrsengel** [ASRG/asrg.io#31]
It makes sense to set up a Github Action that automatically uploads updated and new files that were pushed to master. We can use [this one](https://github.com/SamKirkland/FTP-Deploy-Action).

@heldyboy can you set up another ftp user and add the credentials to the configuration? Otherwise just send it to me via mail and I can try to set it up. My public key can be found [here](https://gist.githubusercontent.com/chrsengel/4f5841bf09da7822bc3e60689bf879ec/raw/220b624ea27097f6dbbc878e95255abcb202e47c/engel-pubkey.asc).

**Comment by heldyboy** [comment]
Done... seems to work. But now the website is down.  I think it's a permissions problem.  Can you take a look as soon as possible?  Thanks.

**Comment by chrsengel** [comment]
The action works as it should I think. The problem was either the httpd config or the DNS settings. I fixed it by refreshing both in the dreamhost panel.
