### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#32]
Can we use the meetup API to gather all the upcoming events for the webpage?

**Comment by chrsengel** [comment]
I think we can set up a feed [like this](https://www.meetup.com/meetup_api/feeds/). We could create a new meetup account, join all ASRG groups, synchronize the meetup calendar with the google calendar according to the guide and then publish the calendar as I suggested in #24. 

We can't use the regular API for this as we would need a token and don't have a server backend (yet). It would be a terrible idea to use the token on the static page 👨🔫.

**Comment by heldyboy** [comment]
The problem with putting all the meetups on one account is that they want to charge around 150 Eurs per month. Not really possible for us. I’m going to look into alternatives for meetup. I was hoping that LinkedIn was going to publish a competitive product but I haven’t seen it yet.

**Comment by heldyboy** [comment]
Actually, I think we can attach all the different calendars in a google calendar... not quite sure how... but I will work on it after christmas.
