### ISSUE TITLE
Twitter Feed

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#33]
Can we add a twitter feed to the main page of www.asrg.io?

**Comment by heldyboy** [comment]
Actually, can we use the twitter feed for the blog right now?  We can make it better later, however I'm adding a lot of stuff to the twitter feed...

**Comment by chrsengel** [comment]
Yeah it's already on asrg.io/blog I think. I just added it to the main page. You can adjust it on the [Twitter Publish page](https://publish.twitter.com/?maxheight=800&query=twitter.com%2FAutoSecResGroup&widget=Timeline) and just update the code.

**Comment by heldyboy** [comment]
Can you please update the background of the blog page to match the twitter background?

**Comment by heldyboy** [comment]
![70FC6FD8-D2CB-4FBD-AD36-6ED62A8CDC46](https://user-images.githubusercontent.com/26025574/71383268-ddf35a00-25db-11ea-9a46-68a5b09fe15c.jpeg)

**Comment by chrsengel** [comment]
Done.
