### ISSUE TITLE
Docs is offline

### ISSUE THREAD

**Issue by chrsengel** [ASRG/asrg.io#34]
The docs are still offline. Looks like dreamhost reset the CNAME to some weird google host. The correct value should be `hosting.gitbook.com`.

![image](https://user-images.githubusercontent.com/32718302/71326873-035f6580-2501-11ea-8250-5aa91e82ac91.png)

We need to get in touch with dreamhost about this as this field is not editable.

**Comment by heldyboy** [comment]
I updated the CMAKE settings, contacted customer support and refreshed the DNS.  Might take up to 12 hours...

**Comment by chrsengel** [comment]
It's back.
