### ISSUE TITLE
Change the ASRG text on the Homepage

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#35]
Can you please change the text ASRG to the logo on the homepage?
<img width="555" alt="Screen Shot 2019-12-24 at 09 30 07" src="https://user-images.githubusercontent.com/26025574/71403467-2177b380-2630-11ea-80ab-4be24fe76398.png">

**Comment by chrsengel** [comment]
I tried the logos in the Google Drive Logo folder but none of them look good on the page. Imo it's impossible to do with the given contrasts.

![image](https://user-images.githubusercontent.com/32718302/71451193-21cb9800-2771-11ea-9c59-3cabc42dc20a.png)

![image](https://user-images.githubusercontent.com/32718302/71451198-4de71900-2771-11ea-8e0b-60f53b271e32.png)

![image](https://user-images.githubusercontent.com/32718302/71451215-930b4b00-2771-11ea-9837-0dfecd0316cb.png)

**Comment by heldyboy** [comment]
Try this one... 
![ASRG_Logo_white](https://user-images.githubusercontent.com/26025574/71475455-8e31b000-27e0-11ea-95d9-ed8bf15f15d2.png)

**Comment by heldyboy** [comment]
Nevermind... I figured it out.
