### ISSUE TITLE
Events: Request to present an ASRG Webinar

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#357]
Use Case: Someone would like to present at ASRG.  The interested party would then submit a form through the ASRG website. 

Create Form that would allow for someone a request to give a presentation at ASRG Webinars.

**Comment by heldyboy** [comment]
@donald-king added a form as the first step.  When someone enters the information into the form, it goes into "entries" and sends an email to the admins.  We would like to have this one step further, that the form automatically starts a new event entry with the type "ASRG Webinar" and starts to fill the information directly into the event. 
The idea is that this is the first part of the process.  After, we have reviewed the submission, we will look for the next open date, add the date and then an email will be automatically generated, "your submission has been accepted and planned for XXXX, please follow the link and add the additional required information".  When the user clicks on the link in the email he/she will see the next form with all the information needed for the ASRG Webinar Event. 

Process:
First Form -> Event Started -> Reviewed by ASRG and Date Added -> Email Sent to Presenter (approve / deny) -> Fill out additional information in form -> Event Updated based on Form -> Manual Release -> Event Published -> Social Media posts sent out (Julian is working on this).

**Comment by heldyboy** [comment]
Need to fix the logo in the email sent to the submitter.

**Comment by heldyboy** [comment]
Current Implementation: Website Form -> WPForms -> WPForms Entry
Target Implementation: Website Form -> XXXXX -> A New Pending Event in the Events Calendar Plugin.

**Comment by heldyboy** [comment]
Community Events is also a possibility. 

Current Community URLs:
Community base: https://www.asrg.io/events/community/
List events: https://www.asrg.io/events/community/list/
Add event: https://www.asrg.io/events/community/add/
The following are always appended by an event (or post) ID

Edit event: https://www.asrg.io/events/community/edit/event/
Edit venue: https://www.asrg.io/events/community/edit/venue/
Edit organizer: https://www.asrg.io/events/community/edit/organizer/
Event delete (deprecated): https://www.asrg.io/events/community/delete/

**Comment by donald-king** [comment]
WP Forms can export submissions in a CSV file. It also uses the Action Schedule WP library. Need to check if exports can be done automatically.

**Comment by heldyboy** [comment]
Due to the website availability, Don was not able to review.  He will work on it this week.
