### ISSUE TITLE
Add Link to Slack at the Bottom

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#36]
Can you please add a icon and link to the slack channel (with the same style)?

<img width="594" alt="Screen Shot 2019-12-24 at 12 36 59" src="https://user-images.githubusercontent.com/26025574/71411564-247f9d80-264a-11ea-9d3b-dc0bed017569.png">

**Comment by chrsengel** [comment]
Can you share the link? I don't have the current one as I don't use slack anymore. [This one](https://join.slack.com/t/asrg/shared_invite/enQtNTYzMjE5NDcyMzUyLWZmMzBhYTRmMzIzZDMyODA5NDkwZDc0Y2EwMDc5NjM2ODhlYWM5NjVlZjY3OWQyMGZhMDljNWI5ZDI1OWUzMDc) doesn't work anymore.

**Comment by chrsengel** [comment]
Got it from the docs.
