### ISSUE TITLE
Event Site: Need to add the video and presentation slides for previous webinars.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#360]
- Changing the template to include this content
- Updating the previous events with the videos and presentations slides.

**Comment by heldyboy** [comment]
@donald-king can you please take a look at this.... we want to add video and the presentation slides to the event web pages.  The event plugin that we are using is called "The Events Calendar".  It would be great if you could do a little research and see how we can add content to the template (pdf and video).  For the PDF it could be as simple as link to the document but should be uploaded to the website (not an external link like google drive or something). The video could be as simple as a youtube video embed.  Thanks sir.

**Comment by donald-king** [comment]
When editing an event in The Event Calendar there is an _Add Media_ button. You can embed locally hosted videos or insert videos from a YouTube URL.

![image](https://user-images.githubusercontent.com/88675481/138480514-1c516600-5d8b-4397-89a1-4beb5ebf7d10.png)
