### ISSUE TITLE
Add Training Overview Page

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#364]
Page from old website with all the professional / industry training opportunities.

**Comment by heldyboy** [comment]
Information was sent over slack.  Can be added now.

**Comment by heldyboy** [comment]
Still open.  Due to the availablitiy issues, still not done.

**Comment by heldyboy** [comment]
Need to use the python script from Brandon to extract the data from the database. Trainings already done.

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/155000324-bc645f42-36cf-4ff7-ba89-a2bc92cc523b.png)

**Comment by usman-asrg** [comment]
The link of the page is "https://asrg.io/training/"
And I added the company name as well on the list display as we mentioned above.

![image](https://user-images.githubusercontent.com/96944860/155229083-b05e0efc-5242-40f9-b40b-3ce61cb7f1c2.png)

**Comment by heldyboy** [comment]
Hi Usman, looks good, but I have some changes.  

1. Please remove "Company Name:"
![image](https://user-images.githubusercontent.com/26025574/155265453-5677e138-bd4b-45d7-a359-d0432dd2b268.png)

2. Can you remove the "Training" and add a ":"
![image](https://user-images.githubusercontent.com/26025574/155265596-fa083d77-1270-4aa8-97ae-b28fbb7afc72.png)

**Comment by usman-asrg** [comment]
Removed the word Company

![image](https://user-images.githubusercontent.com/96944860/155311539-d5d5744e-5774-43c1-b8bc-bcb57fa27076.png)

**Comment by usman-asrg** [comment]
Added " : " and removed the word Training

![image](https://user-images.githubusercontent.com/96944860/155311880-f23f8b5b-95c3-4be7-ad8f-28c64fdadfe8.png)
