### ISSUE TITLE
Post Webinar Marketing Automation

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#371]
- Add new field
- Add automation to send out social media posts.

**Comment by JB4dev** [comment]
New field for post webinar marketing text "acf_social_media_text_after_webinar_promotion" available in the event editor

**Comment by JB4dev** [comment]
added "Social media text to promote the event after it has happend." field in the events editor. Posts on social media will be scheduled 3 days after the event (webinar@Thursday 6pm -> post marketing@Sunday 6pm)

**Comment by JB4dev** [comment]
@heldyboy FYI
