### ISSUE TITLE
Add the Event Calendar Community and setup correctly.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#372]

**Comment by donald-king** [comment]
Event Calendar can import events in a CSV. Working on getting WP Forms CSV export functionality automated before importing events into Event Calendar.

**Comment by donald-king** [comment]
![image](https://user-images.githubusercontent.com/88675481/135129157-b0dba94d-aaef-43ff-8ce1-2eab8ac5cabe.png)
WP Forms exported CSV creates this when imported with Event Calendar

**Comment by heldyboy** [comment]
@donald-king is going to take a look at the events community plugin.

**Comment by heldyboy** [comment]
https://www.asrg.io/wp-admin/edit.php?page=tribe-common&tab=community&post_type=tribe_events

- Setup Recaptcha
- Test

**Comment by heldyboy** [comment]
Due to the website availability, Don was not able to review.  He will work on it this week.
