### ISSUE TITLE
New Account VAlidation

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#373]
Problem: Everyday we are getting 100's of new accounts. 
Solution Proposal: Introduce a email / account field validation plugin for wordpress. 

This should be SMS or One Time Code.

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/135889457-c52afda0-4e30-4275-a218-93ac2d1704b7.png)

**Comment by heldyboy** [comment]
Need to add SMS verification

**Comment by heldyboy** [comment]
@KellyDSD we need a good recommendation for a one Time Code or a SMS verfication strategy.  We would like to reduce the amount of not real registrations.

**Comment by KellyDSD** [comment]
We can add in email One time code verification for this easily enough - again best to wait 5-7 days to check firewall set up and spam honeypot
