### ISSUE TITLE
Add HSTS Policy

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#377]
https://digital.com/best-web-hosting/wordpress/security/

**Comment by donald-king** [comment]
`add_header Strict-Transport-Security max-age=10886400;
add_header X-Xss-Protection "1; mode=block" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Content-Security-Policy "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';";`

These headers were added to the nginx.conf file and resulted in no change to the results on securityheaders.com

**Comment by usman-asrg** [comment]
According to the link you shared above I found the way to add HSTS header
![image](https://user-images.githubusercontent.com/96944860/148828743-8b36aed3-3b69-424f-98c7-23ec0fb66a66.png)

**Comment by usman-asrg** [comment]
@heldyboy  By following the instructions I have added the HSTS header.
![image](https://user-images.githubusercontent.com/96944860/148828934-e416d177-fcd1-4a54-9248-db84e82bc971.png)
