### ISSUE TITLE
Need to add the "Add Event" button to webinar and conferences pages.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#378]

**Comment by donald-king** [comment]
Need to add wrapper around button and put button on pages.

**Comment by heldyboy** [comment]
Need to understand how to add the button (with the authenification wrapper) to the Events List Page.

**Comment by donald-king** [comment]
1. The configuration file to edit the top bar of the events page regardless of what view is being used is located at [wp-content/plugins/the-events-calendar/src/views/modules/bar.php](https://theeventscalendar.com/knowledgebase/k/calendar-template-files-v2/#:~:text=an%20event%20single.-,modules/bar.php,-Renders%20the%20events). 

2. To edit the page view without your changes being overwritten when the plugin is updated create a new folder named tribe at [/wp-content/themes/*your-theme*/](https://theeventscalendar.com/knowledgebase/k/customizing-template-files-2/#:~:text=So%20far%2C%20you%20should%20have%20a%20new%20folder%20in%20your%20theme%20located%20at%3A%C2%A0/wp%2Dcontent/themes/your%2Dtheme/tribe/).

3. Add another folder inside tribe as directed [depending on what view is being used](https://theeventscalendar.com/knowledgebase/k/customizing-template-files-2/#:~:text=The%20Events%20Calendar%20(legacy%20views)).

4. You should then be able to copy the config file (wp-content/plugins/the-events-calendar/src/views/modules/bar.php) over to the new folder and edit it there in the theme. Any changes made to the new file in the theme directory will take precedence over the original configuration without getting modified when the plugin is updated.


[Here is a list of all the template files](https://theeventscalendar.com/knowledgebase/k/calendar-template-files-v2/) if bar.php is the incorrect file or if you want the button on a different part of the page.

[Here is the detailed guide on customization](https://theeventscalendar.com/knowledgebase/k/customizing-template-files-2/) and instructions for how to copy the template file to the theme.

[Here is a practical example](https://theeventscalendar.com/knowledgebase/k/template-customization-example/) of a template customization.

**Comment by heldyboy** [comment]
No longer needed.  We are using the Community Events to add events to the website.
