### ISSUE TITLE
Setup a Newsletter Sign Up Form

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#38]
Need to create a newsletter sign up form on the website.

**Comment by chrsengel** [comment]
We have to setup our own service and database or use an existing provider. There's a couple of great providers out there. Here's a short overview of the services I know.

| Provider                                    | Monthly Price              | Discount                | Price after Discount | Notes                                                                                                                                                                                                                                    |
| ------------------------------------------- | -------------------------- | ----------------------- | -------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [Revue](https://www.getrevue.co/pricing)    | \$24 for < 4k subscribers  | -                       | -                    |                                                                                                                                                                                                                                          |
| [Mailchimp](https://mailchimp.com/pricing/) | \$50 for < 5k subscribers  | 15%                     | \$42.5               | Has probably the best templates and event management. You can easily create a nice workflow. E.g. `register` => `confirm` => `welcome`. Also supports nice tracking features.                                                            |
| [Sendy](https://sendy.co/)                  | <\$1 at 4k mails per month | -                       | -                    | Uses [Amazon SES](https://aws.amazon.com/ses/). Therefore requires lots of manual configuration and creating email templates kind of sucks. It's not like modern HTML. I suggest using [mjml](https://mjml.io/) if we were to go this route. I'm using this for dethlify. |
| [SendInBlue](https://sendinblue.com)        | 19€ at 40k mails per month | Yearly payment discount | 17.10€               | Looks like Mailchimp.                                                                                                                                                                                                                    |

**Comment by heldyboy** [comment]
Awesome overview, thanks.  From your point of view, which one is the easiest to manage and still looks professional?

**Comment by chrsengel** [comment]
Imo the one we can get the most value out of is mailchimp. If we have the budget I'd use that service. If not, then I suggest we simply try out multiple ones. All services allow you to export all contacts so switching is rather simple.

**Comment by kaipyroami** [comment]
Mailchimp is always a good choice
