### ISSUE TITLE
Need to investigate why Google Site keeps thinking we changed an IP address.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#392]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/143409479-7b1b6b46-9b8d-4726-b887-8ad87333e9b0.png)

**Comment by usman-asrg** [comment]
@heldyboy I searched about this error its basically having compatibility issue with the WPML language plugin and one more language plugin. We have only this "GeoDirectory Multilingual" plugin which is working with WPML. But we don't have any WPML plugin. So may be this will be the reason of it. 
Can you tell me if you have any information related to the use of "GeoDirectory Multilingual" this plugin ?

**Comment by usman-asrg** [comment]
@heldyboy This is what I am seeing. 

![image](https://user-images.githubusercontent.com/96944860/149311590-5b4f56fc-8f37-4631-a7fb-af8c0fd3017b.png)

**Comment by heldyboy** [comment]
@usman-asrg Ok, I just updated it yesterday.  We can close this topic for now... if it comes up again, then I will re-open the ticket.
