### ISSUE TITLE
2FA not working.  Can you please take a look at the 2FA function in Wordpress?  We should remove the requirement of having 2FA and have a requirement of one time code or sms during the registration.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#395]
Users can not complete the 2FA requirement. 

![image](https://user-images.githubusercontent.com/26025574/143435028-7e5414f8-8546-425f-a0d7-b43fab87a908.png)

**Comment by KellyDSD** [comment]
2FA has been removed as this was causing conflicts on login - researching into options of OTP registration - best to let Wordfence in this case run for a day first to ensure no further issues that side

**Comment by KellyDSD** [comment]
I have set Wordfence in motion and a spam extension which I think will cover this off. We can look at OTP also but I Would leave this in motion for a week to check

**Comment by heldyboy** [comment]
@usman-asrg Please add additional information and what is needed to implement your proposal. (Technical changes, how many hours).

**Comment by usman-asrg** [comment]
@heldyboy  I have looked into it once more. We can use "Ultimate Member Registration" plugin for the profiling of user. in that case can integrate the "miniOrange OTP Verification Plugin" with this and we get rid of the USERWP plugin also. this will take less time than coding with JavaScript... open for the suggestion from your side.

**Comment by heldyboy** [comment]
@usman-asrg I think we looked at this option already, but can you please let me know the costs.

**Comment by usman-asrg** [comment]
I think I required 2-3 hours for all the testing and implementation of Email OTP

**Comment by heldyboy** [comment]
This will not be done for now.
