### ISSUE TITLE
ASRG Security Awareness Training

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#396]
Build a slide deck with awareness training topics for automotive security.

**Comment by heldyboy** [comment]
~50%. Content and outline is available, just need to put together in slides. Waiting for feedback from BH.

**Comment by donald-king** [comment]
Initial content is ready - will be stripping out company specific information week of 2/21/2022

**Comment by heldyboy** [comment]
@donald-king delivered the content in zip format.  

@usman-asrg 
Create a new Page "Automotive Security Awareness"
Copy the content into the new wordpress site.  
Make sure all the images / content and links are working correctly. 
Add to Menu under Learning.

**Comment by usman-asrg** [comment]
@donald-king  Hey can you deliver the content in zip format that John is talking about ? Thanks

**Comment by donald-king** [comment]
@usman-asrg Here it is. [Export-cdffc67a-ac39-49ca-b110-c318884f5dfd (1).zip](https://github.com/ASRG/asrg.io/files/8226107/Export-cdffc67a-ac39-49ca-b110-c318884f5dfd.1.zip)

**Comment by usman-asrg** [comment]
Thank You @donald-king

**Comment by usman-asrg** [comment]
https://asrg.io/automotive-security-awareness-training/

The Menu is added and its live
