### ISSUE TITLE
Update template for Registration

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#405]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/149980483-64ea705e-7bbb-4fa0-b7ff-3f891af0b0fa.png)

Please remove the Register text marked in RED.

**Comment by usman-asrg** [comment]
The template is fixed
![image](https://user-images.githubusercontent.com/96944860/150029675-0b421dca-ca8c-4bef-96f4-85f5390d6f7b.png)
