### ISSUE TITLE
ASRG Dashboard

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#41]
Can we take over this code from PyLadies and adapt it for ASRG website? 

https://github.com/nyc-pyladies/pyladies-dashboard

**Comment by chrsengel** [comment]
The code over there is pretty messy and to be honest I don't think it looks that good. But it's a nice dashboard template we can use as a reference. I just put together a first draft for our dashboard in the [feature/dashboard](https://github.com/ASRG/asrg.io/tree/feature/dashboard) branch.

It uses React and is pretty simple so far. You can check it out on [chrengel.com](https://chrengel.com) if you don't want to build it yourself locally.

React is awesome as we can easily build more and more widgets into the dashboard. Right now it uses static data but once we figure out how to export the meetup data, we can fetch the data periodically, store it in a single `json` or `csv` file and then load it from the webapp. That's how the pyladies dashboard does it.
