### ISSUE TITLE
Social Media Login

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#411]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/152104262-ede1a4b1-2b5a-4092-93e1-ab9d24c2038f.png)

**Comment by usman-asrg** [comment]
We Need API's... So we can enable this social login feature

**Comment by heldyboy** [comment]
Meeting setup for thursday.

**Comment by usman-asrg** [comment]
Login Via Google is activated and tested successfully, but we are working on Facebook and linked-in
