### ISSUE TITLE
Fix the Pages in Automotive Security Suppliers

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#413]
The pagination for the directories is not professional.  Need to check what the problem is. 

![image](https://user-images.githubusercontent.com/26025574/152110020-ca42775b-674f-41e5-946c-a8ec76932866.png)

**Comment by usman-asrg** [comment]
@heldyboy  This is fixed :

![image](https://user-images.githubusercontent.com/96944860/153927416-af3cacfd-e16f-4bdb-9e1a-ababd13c0255.png)
