### ISSUE TITLE
Automate the Embed Link for Youtube in the Events

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#417]
We should take 

https://www.asrg.io/wp-admin/post.php?post=13640&action=edit

![image](https://user-images.githubusercontent.com/26025574/153912900-2343fc17-2055-4bb1-b9bb-b109bbf134c0.png)

and auto generate the embed link and populate the field. 

![image](https://user-images.githubusercontent.com/26025574/153913016-647d74ed-ef44-4f8a-ada6-9219e4e047ed.png)

**Comment by usman-asrg** [comment]
@heldyboy Now the Iframe is automated. It will grab the last word of the URL and we don't need to copy embed code for every video out there...

![image](https://user-images.githubusercontent.com/96944860/154346849-dbb813f0-5174-4f58-b279-ffe534164cd2.png)

**Comment by heldyboy** [comment]
It seems like the embed automation is not working completely. Please review the following. Link. 

https://www.asrg.io/event/fuzz-testing-automotive-software-with-dependencies/

**Comment by heldyboy** [comment]
@usman-asrg Please review these links which are not working. 

https://www.asrg.io/event/security-and-privacy-of-electric-mobility-threats-and-possible-solutions/
https://www.asrg.io/event/v2rf-assessing-cars-rf-communications-2/
https://www.asrg.io/event/accenture-cyber-security-garage/
https://www.asrg.io/event/powersports-and-recreational-vehicle-networks/

**Comment by usman-asrg** [comment]
These links are fixed now... The issue was with the Video link... I updated
the link and the embed link is start working

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/157082673-6c2fa54f-e539-42a9-94bb-ee4b7f71f350.png)

Need to fix a templating issue.

**Comment by usman-asrg** [comment]
@heldyboy Following links are fixed now

https://www.asrg.io/event/security-and-privacy-of-electric-mobility-threats-and-possible-solutions/
https://www.asrg.io/event/v2rf-assessing-cars-rf-communications-2/
https://www.asrg.io/event/accenture-cyber-security-garage/
https://www.asrg.io/event/powersports-and-recreational-vehicle-networks/

![image](https://user-images.githubusercontent.com/96944860/157303537-ea6fedd2-b5e5-409d-b726-4746ed141425.png)

**Comment by heldyboy** [comment]
should only occur when Event Type is ASRG Webinar.

**Comment by usman-asrg** [comment]
@heldyboy  Now it will only occur when event type is ASRG Webinar.
