### ISSUE TITLE
Fix the Content Control Short code in the Benefits page posts.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#418]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/153917085-724492aa-ffaa-426c-a5ce-cd2dd7301284.png)

https://www.asrg.io/wp-admin/post.php?post=15616&action=edit

**Comment by usman-asrg** [comment]
@heldyboy    We need to update the shortcode for this: The updated shortcode will be the following

[content_control roles="subscriber,editor,administrator,author" message="Register to Access Discount Codes"]CYRES4ASRGACPL1[/content_control]

Then you will able to see the code as display in the screenshot

![image](https://user-images.githubusercontent.com/96944860/154133546-bd75f792-18c5-42ab-ad36-f914cbb5fe28.png)


If you are not logged in then you will see the following message

![image](https://user-images.githubusercontent.com/96944860/154133653-bfa7e1d7-9a4e-4e6c-bdc6-926f8cb80ead.png)
