### ISSUE TITLE
Template Corrections

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#419]
Please correct the following template issues.... 
https://www.asrg.io/profile/

![image](https://user-images.githubusercontent.com/26025574/154212574-a0223819-ca69-4f89-8658-54edf1771fc7.png)

**Comment by usman-asrg** [comment]
@heldyboy The issue of the template is fixed now.

![image](https://user-images.githubusercontent.com/96944860/154356204-af521e30-ff57-41a8-8b2b-4ebce5cb0ef5.png)

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/154999695-4e23e0f1-5b70-40bb-a09a-ccf0b81831d0.png)

**Comment by usman-asrg** [comment]
This is Fixed
![image](https://user-images.githubusercontent.com/96944860/155041994-aa96322b-aec5-4fd3-9490-e9d8c70c2721.png)
