### ISSUE TITLE
Add Information and Logos to Training posts

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#420]
Plase add all the logos to the training posts as featured image, and add the meta data (price, etc.) to the post template.  After this we will work on the formatting.

**Comment by usman-asrg** [comment]
All the Meta Data is now Visible to the training posts

![image](https://user-images.githubusercontent.com/96944860/155225422-1c5675b4-5ba3-4f0a-9cba-b369a39001ed.png)
