### ISSUE TITLE
Training Post Template Update

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#421]
Please remove the meta data from training / benefit posts. 

![image](https://user-images.githubusercontent.com/26025574/154215193-57531673-f202-47fe-805c-c75ab60a8272.png)

**Comment by usman-asrg** [comment]
@heldyboy The meta data from the "Benefits" & "Trainings" posts are removed:

![image](https://user-images.githubusercontent.com/96944860/154358000-97d1a1b6-4ba4-45f4-b4c5-9cfaef662147.png)

![image](https://user-images.githubusercontent.com/96944860/154358365-64d7f172-19a4-4d30-b617-d944c746d12c.png)
