### ISSUE TITLE
Add CYRES Training / Benefit Information in Website

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#422]
As post for benefits and paid-training.  See email. 

https://www.asrg.io/acp-level-1-foundation-training-from-cyres/

**Comment by usman-asrg** [comment]
The second one is also posted according to the sample you shared, here is the link

https://asrg.io/acp-level-2-advanced-engineering-training-from-cyres/

**Comment by heldyboy** [comment]
Can you please remove the "-"?  It should just be a space.
![image](https://user-images.githubusercontent.com/26025574/155265943-9496900d-abaa-4c8f-a7c4-c4cbc071ac90.png)

**Comment by heldyboy** [comment]
Also, can you please update the template to have the information regarding the training aligned... 

And please link the company name to the automotive supplier directory page. 
![image](https://user-images.githubusercontent.com/26025574/155266261-9c566033-a4c6-425e-a63e-27639e05dc7e.png)

**Comment by heldyboy** [comment]
Also, please add the 3rd training opportunity, the internet based training. Let me know when you add it so I can review, update and release.

**Comment by usman-asrg** [comment]
Done with the allignment

![image](https://user-images.githubusercontent.com/96944860/155313323-1d683c4b-3232-4f41-8593-fb5ac05595e1.png)

**Comment by usman-asrg** [comment]
Here is the 3rd one and you can find it under the post as a draft.

![image](https://user-images.githubusercontent.com/96944860/155316521-c82d7bad-bbd0-4b19-846e-1d0c565180c8.png)
