### ISSUE TITLE
In webinar page, presentations should be as a Icon with a file name beside it.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#423]
We want to upload a file (presentation slides) to each event. This should be a new field in each event.  When there is data, then a file icon (favicon) should be present in the webpage with a file name. The link and icon should only be visible after the presentation date. 

![image](https://user-images.githubusercontent.com/26025574/155001461-2874fc07-2e5c-4cd6-a25b-7064e37f81dc.png)

**Comment by usman-asrg** [comment]
@heldyboy  I added the code for this scenario: When you edit any Event there will be a custom meta file field with the name of Presentation File: Can you just try to add any presentation file into any event? and share the link?

There are the following conditions that I have added: 

The file will only be visible when The event date is passed:
Also if the file is available. 

![image](https://user-images.githubusercontent.com/96944860/156474552-319b8931-63e8-4eea-bc2f-a39d6c3ea8c3.png)

**Comment by usman-asrg** [comment]
I test the code into the localhost here is the view:

![image](https://user-images.githubusercontent.com/96944860/156474808-140524fb-584b-45f2-b2a1-0327f3210cec.png)

**Comment by heldyboy** [comment]
Looks good. Please implement.

**Comment by usman-asrg** [comment]
@heldyboy  can you share any presentation file for ant event so I can test this ?

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/157084474-17b107b5-def9-4cd9-a0e1-c8ca1c69eddb.png)

**Comment by usman-asrg** [comment]
@heldyboy I removed one file and replace its location
Here is the URL
https://asrg.io/event/powersports-and-recreational-vehicle-networks/

Here is the view... also, Do you want me to update all the events just I did this one ?

![image](https://user-images.githubusercontent.com/96944860/157323099-daace96a-4e5e-4db7-9c3c-47ce10c8c33e.png)

**Comment by heldyboy** [comment]
@usman-asrg has changed all the presentation links to the new field.
