### ISSUE TITLE
Feature Photo is Automotive Suppliers directory should not be stretched, but fit.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#424]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/154946761-574d902f-99e7-4b00-b268-5d3b6a1451c2.png)

**Comment by usman-asrg** [comment]
Now the all logos will be not stretched out...

![image](https://user-images.githubusercontent.com/96944860/155042422-f76976ab-d543-4717-a3ec-6c856e2ce27b.png)
