### ISSUE TITLE
Add Secure Code Warrior Training as Post

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#425]
Information sent in Email.  
Post should be with Benefits and Free Training tagged.

**Comment by usman-asrg** [comment]
Post have been added with the Benefits and Training Tag

![image](https://user-images.githubusercontent.com/96944860/155097037-b222c914-b475-4a88-a946-f4d7b7a8ea13.png)

**Comment by heldyboy** [comment]
I have reviewed and updated.
