### ISSUE TITLE
In Related Items, the picture is stretching and not seeable.  Can you please fit the images?

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#426]
https://www.asrg.io/embedded-automotive-security-a-hands-on-introduction/

![image](https://user-images.githubusercontent.com/26025574/155266490-edbe0d62-2e3e-4505-a145-2cc1e82c4daa.png)

**Comment by usman-asrg** [comment]
in related article the image issue is fixed

![image](https://user-images.githubusercontent.com/96944860/156253684-f21f1619-2de6-4124-994b-ec6f22604ec1.png)
