### ISSUE TITLE
Automotive Supplier Directory: Address City, Country Missing.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#427]
Please make sure that the full address is being displayed correctly.  Thanks. 
https://www.asrg.io/directory/c2a-security/
![image](https://user-images.githubusercontent.com/26025574/155270520-ad3d9159-ab4f-450f-b00b-618f73371fb9.png)

**Comment by usman-asrg** [comment]
@heldyboy  The city country issue is resolved

![image](https://user-images.githubusercontent.com/96944860/163742172-7cc66456-a1bf-463b-9c47-f3b5bf69c2ca.png)
