### ISSUE TITLE
Resolve WordFence Scan Issues

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#428]

**Comment by heldyboy** [comment]
https://www.asrg.io/wp-admin/admin.php?page=WordfenceScan

![image](https://user-images.githubusercontent.com/26025574/155841829-ce6dcd27-f83b-40f1-b079-29fcd0007dc9.png)

**Comment by usman-asrg** [comment]
The Issue is resolved for wordfence

![image](https://user-images.githubusercontent.com/96944860/156233549-00e84eff-1c17-4d7b-917e-30d8ca695fed.png)
