### ISSUE TITLE
Find all mentions of ASRG in the Press and add to the ASRG Website as a Post.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#434]
https://www.asrg.io/about-us/asrg-in-the-press/

**Comment by usman-asrg** [comment]
I found 4 News... and those are posted https://www.asrg.io/about-us/asrg-in-the-press/

**Comment by heldyboy** [comment]
https://drive.google.com/drive/u/0/folders/1gjaG1Z9jqXQND9NVpIz5Z9TgpzipAfS8

**Comment by usman-asrg** [comment]
@heldyboy  Please give me an access to view this above link

![image](https://user-images.githubusercontent.com/96944860/162858811-97af4001-50db-42d3-a67f-e4275e641e5a.png)
