### ISSUE TITLE
Fix "Send Us a Message" link in Contact us Page

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#435]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/159724964-dd85a056-0711-4371-ae9b-e62fa017c3ba.png)

**Comment by usman-asrg** [comment]
@heldyboy  The link is added to the Send us a message. Do we need a contact form as well ?

**Comment by heldyboy** [comment]
Please make a contact for as well.

**Comment by usman-asrg** [comment]
Contact Form is added

![image](https://user-images.githubusercontent.com/96944860/161732147-4267f1c7-2122-4519-9ed0-4246d2745268.png)
