### ISSUE TITLE
Update Social Media Icon in Login Page

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#440]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/160447822-296a0b35-f23d-427e-ae4e-6e4570e9a3e9.png)

**Comment by usman-asrg** [comment]
Icons are fixed on both registration and login pages

![image](https://user-images.githubusercontent.com/96944860/160478100-ee6cecf2-a097-49bc-9c53-49adc462d6f7.png)
