### ISSUE TITLE
Fix WP Links Plugin

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#442]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/160449056-316c7d54-4943-4023-acef-bf6fdc8b0345.png)

**Comment by usman-asrg** [comment]
@heldyboy  I have found an alternative of WP Links plugin. Its called "Simple Link Directory Plugin" You can see the below screenshot and we can now add links and create a list of links and display on that specific page. 

![image](https://user-images.githubusercontent.com/96944860/162853373-35566cfe-0028-4903-bb2c-f40b056741da.png)
