### ISSUE TITLE
Update the participating universities

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#443]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/160449253-de91b7da-99fa-4158-98d5-3d563b4b9f8c.png)

https://www.asrg.io/networking/academic_network/

We want to use the logos short code to display the logos better. The sponsors are done this way on the home page.

**Comment by usman-asrg** [comment]
Updated the logos as a shortcode and added all the logos in the University Category.

![image](https://user-images.githubusercontent.com/96944860/161735905-970566b6-6d6b-4c36-ae63-c6cd4d8c13e0.png)
