### ISSUE TITLE
Review the loading delay / performance of the website loading.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#448]
Please make sure to capture the improvement of the performance characteristics.

**Comment by usman-asrg** [comment]
@heldyboy  I am thinking not to work on this topic, as we are already planning to redesign the website. So we need to focus on that. Once that finalize we will then do the optimization into our new website. But, if you want me to do the optimization for this one also, then just let me know

**Comment by usman-asrg** [comment]
I think now the loading and everything is fine so we can close this task
