### ISSUE TITLE
Install development / staging environment for the website.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#449]

**Comment by usman-asrg** [comment]
@heldyboy  I need access of Azure Server. So I can create staging environment for website redesign

**Comment by heldyboy** [comment]
Hi Usman,

Please let me know what you would like to do before I give you access to
the Azure Instance.

**Comment by usman-asrg** [comment]
Well, I need to install the WordPress for staging environment. That's it..
If you can do that then just share the logins details of staging environment .

**Comment by heldyboy** [comment]
@usman-asrg But what do you need exactly?  A seperate VM setup? We want something that we can version and push to the production site.

**Comment by usman-asrg** [comment]
@heldyboy  Yes, exactly we need to create staging Deployment Slot. Once we will finish our process of revamping the site we will deploy the changes to our live site.
