### ISSUE TITLE
ASRG Website Project - create the tasks and timeline (Discuss on 27 June 2022)

### ISSUE THREAD

**Issue by rinaespiritu01** [ASRG/asrg.io#452]

**Comment by usman-asrg** [comment]
@prabath-asrg  Hey are you available tomorrow to discuss this task ? If yes let me know the time so we can schedule our meeting

**Comment by prabath-asrg** [comment]
@usman-asrg Sure we can schedule a meeting in the evening. BTW I am not fully completed with analysing the site. In terms of UX, there are significant problems to address.

**Comment by usman-asrg** [comment]
I see... okay then take your time.
We'll do this on next week then...
