### ISSUE TITLE
Please create a Landing Page for the SOS conference.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#456]
Prabath we need a simple and clean landing page for the SOS conference.  We have 3 pages that need to get this style.  Please find the existing pages here.  This needs to be completed as soon as possible. 

https://www.asrg.io/sos/sos2022/

Logo:
https://drive.google.com/file/d/18VZAjgEy8J_NQE8zOf8g3C7s15G7dWTH/view?usp=sharing

**Comment by prabath-asrg** [comment]
Sure I will design this by Sunday Morning. Just two quick questions.

1. Are we using the same content from the current page? Or do we update the content?
2. The design style for this page should be the one I presented yesterday or the current one on the site?

**Comment by prabath-asrg** [comment]
@heldyboy 
Please check the SOS landing page I designed. I have created a confluence doc for remarks and edits and separated it into sections. Please leave a comment there if there is anything needed to be changed.
Confluence doc: https://internal-confluence.asrg.io/x/FQDDAQ
Figma design: https://www.figma.com/file/iCZ6BJ4IG4fY8J2qFaDN6W/ASRG.IO-SOS-Landing-Pages?node-id=0%3A1

**Comment by prabath-asrg** [comment]
Sponsorship Opportunities page designed and can check using Figma file and can add comments on confluence.
