### ISSUE TITLE
Need to update the style of the recent events on garage.asrg.io

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#457]
![image](https://user-images.githubusercontent.com/26025574/185810479-b46382fe-e94e-44ea-81c8-36ef44b1565b.png)

**Comment by prabath-asrg** [comment]
If this is about the white space above the month it shows only when editing the page and when you view the site it looks fine. But if you need a completely new way of design I can do that.

**Comment by heldyboy** [comment]
Looks good.  But we need to sort the list with the next event first.

**Comment by prabath-asrg** [comment]
Done. Now it only shows the upcoming events and sorted from closest date to farthest date.
