### ISSUE TITLE
Need to correct the news post layout.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#458]
The news layout needs to be laid out better.  We should discuss the requirements together in the monday meeting. 

![image](https://user-images.githubusercontent.com/26025574/185810690-76c5207b-24d5-4615-a8ad-a6d17aea6486.png)

Changes:
- The links to share on social media should have "Share on" or something like this to identify that we should share.  
- The pictures are redunant.  We probably just need a simpler layout here. 
-

**Comment by prabath-asrg** [comment]
Added the "share on" phrase. The image looks wired because the same image appears on the same screen, I suppose. The reason for that is that Ikjot's same image has been used as the featured image and an image in the post.
