### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#459]
Changes:
- Locations does not go anywhere (https://garage.asrg.io/account/locations/)
- Need to add "My Projects" to the menu list.
- What is the difference between Locations and Saved Locations
- We should probably add a city field as well. 
- When you add a phone number, it should check the format. 
- When you add a phone number, it should confirm by sending an SMS. 
- When you change the email it should ask to confirm by sending an email.
- When you update your profile, it should go back to the My Profile screen with the profile updated message. 
- The color of the menu buttons and the footer are the same. Need to change this to different colors. 
![image](https://user-images.githubusercontent.com/26025574/185810971-7455d1f9-1ead-4496-94e7-b2a02d4168f6.png)

**Comment by prabath-asrg** [comment]
- Locations do not go anywhere (https://garage.asrg.io/account/locations/) **Removed**
- Need to add "My Projects" to the menu list. **Done**
- What is the difference between Locations and Saved Locations **A user can save their favorite locations so they can access them from "saved locations" easily**
- We should probably add a city field as well. **Done**
- When you add a phone number, it should check the format. **Done**
- When you add a phone number, it should confirm by sending an SMS.
- When you change the email it should ask to confirm by sending an email. **Done**
- When you update your profile, it should go back to the My Profile screen with the profile updated message. **Done**
- The color of the menu buttons and the footer are the same. Need to change this to different colors. **Done**

SMS thing is a long task so will add that as a new card in the todo list

**Comment by heldyboy** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/26025574/187280392-7154e00a-e26e-456b-be97-baaf13a80adc.png">

The phone number format needs to take into consideration all country codes. Maybe a drop down for the country code first and then it will check the format of the expected phone number.

I think the SMS is still not working. Which third party apps might work here? 

Also, at the bottom the last menu item of the profile page needs some more space between the footer and the last menu item.

**Comment by prabath-asrg** [comment]
Regarding the SMS, I am thinking of this plugin https://plugins.miniorange.com/wordpress-otp-verification

I have requested a demo so we can test it before purchasing. Also, we need an SMS gateway to do the OTP verification. These are the gateways this plugin accepts please have a look. https://plugins.miniorange.com/supported-sms-email-gateways

I will fix the account menu and the margin issue is fixed.

**Comment by heldyboy** [comment]
SMS is on hold for now.  Prabath to check with Jet Engine regarding the world wide telephone numbers
