### ISSUE TITLE
Header Updates

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#460]
We need to make the following updates to the header. 
- The profile picture and text should be linked to the profile page. 
![image](https://user-images.githubusercontent.com/26025574/185811331-c9bbed4e-f2d9-4f4e-b5ae-e2e849ea623f.png)
- The logo should be center in above the left main menu bar and vertical center in the header. 
![image](https://user-images.githubusercontent.com/26025574/185811396-540aa3be-5a9b-457c-a1f4-77aa306482b1.png)

**Comment by prabath-asrg** [comment]
Done
