### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#461]
https://garage.asrg.io/locations/

We need to make the following changes. 
- Do we need a breadcrumb?
- The Filter is a great feature. 
- When you select a region as a filter, it takes a minute to load the results.  Can we build in a loading status to show that it is not done yet?
- Why is the search button not centered?  Can we make it square?
![image](https://user-images.githubusercontent.com/26025574/185811576-eddc1246-7282-4f33-ac53-63da7c6c72a2.png)
- Also, please add as the intial text in the search field "Enter search text here..."
- We should change the border color to a lighter gray color
![image](https://user-images.githubusercontent.com/26025574/185811698-285a4516-2bd4-4259-8c2a-aadbd677942e.png)
- I think we should change the card layout as well. My proposal is... 
ASRG-XXX (Centered, Bold)
City, Country
Upcoming Events
Email Meetup 
and the rest the same.

**Comment by heldyboy** [comment]
Basically all text and image in the card should take you to the detail.

**Comment by prabath-asrg** [comment]
Done except the filtering indication and need more time to check whether it is possible
