### ISSUE TITLE
When you click the "Join this Committee", a new page should appear with a form. 

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#466]
This page should have some text, what it means to join this technical committee (how much time, participation in meetings, and etc.) and at the bottom there should be a form pre-filled with information (from their profile)
First and Last Name
What I would like to contribute to the technical committee? (free-text)
(Check-box) I understand that this committee will require time and effort from myself. 
(Check-box) I understand that the work products of these technical committees are to benefit the community and not for the organization that I work for.

**Comment by prabath-asrg** [comment]
Done

**Comment by heldyboy** [comment]
Really Nice!

Appeal -> Request


<img width="503" alt="image" src="https://user-images.githubusercontent.com/26025574/187278795-c2689f35-136a-4b60-82c0-89b3e041634b.png">
"Appeal to become a member under review" -> "Member request under review"

**Comment by prabath-asrg** [comment]
Done
