### ISSUE TITLE
Training Page Updates

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#469]
- Display as Table
- Bring in Logo from Supplier Directory and display in the table and post details.
- update the Style to match the technical committees
- Add Reviews with Ratings
- Add Link to post page to Title Text and Image
- Add Discount Code as text
- Discount code should be at the bottom in Large Font with a copy button next to it. 
- Add Currencies as drop down in post meta fields.
-

**Comment by prabath-asrg** [comment]
- Display as Table - **https://garage.asrg.io/training/**
- Bring in Logo from Supplier Directory and display in the table and post details. - **Done but some companies did not existed in the directory. Also, for some trainings the logo of the company has been used as the featured image. So it's little awkward when the logo appears at two places.**
- update the Style to match the technical committees -**Done**
- Add Reviews with Ratings -**Done**
- Add Link to post page to Title Text and Image -**Done**
- Add Discount Code as text -**Done**
- Discount code should be at the bottom in Large Font with a copy button next to it. -**Done**
- Add Currencies as drop down in post meta fields. -**Done**

**Comment by heldyboy** [comment]
Table looks good.  Need to add the Link to the title and add the picture to the table.
Training Costs -> Costs
Add Sorting for table headers

**Comment by heldyboy** [comment]
Please add Newest to the sort. 
Please change the color of the links in the add new training to normal grey colors.
