### ISSUE TITLE
Reference Posts

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#470]
Meta Fields
- Name (title)
- Type: (Guideline, Link, Publication, Standard, Regulation, etc.)
- Picture
- Description
- Link
- File Upload
Please add these links to the references. 
https://project-awesome.org/jaredthecoder/awesome-vehicle-security

**Comment by prabath-asrg** [comment]
I have added the post type and created the type as a taxonomy. It's better to add the 26 publications/references manually rather than importing them.

**Comment by heldyboy** [comment]
@prabath-asrg Can you please import all the links from the Awesome Vehicle Security page?

**Comment by prabath-asrg** [comment]
I am on it.

**Comment by heldyboy** [comment]
courses -> Trainings
Blogs -> References
Websites -> References
Conferences -> Events
Who to follow -> References
Podcasts and Episodes -> References
Projects, misc. -> References
Hardware -> Hardware
Software -> Software
Applications -> Applications
Libraries and Tools -> References
Companies -> Companies
Coordinated Disclosure -> Disclosure Programs (from the old ASRG website)

**Comment by prabath-asrg** [comment]
@heldyboy everything is added except courses and companies. 
-Some courses are already passed and some have a series of courses.
-The pages related to companies are their job pages.
