### ISSUE TITLE
update the Event Card

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#473]
We don't need the To and From... only start date / Time and duration. 

![image](https://user-images.githubusercontent.com/26025574/186416875-1ab410f7-0514-4dcb-8236-d6dcee313dec.png)

**Comment by prabath-asrg** [comment]
<img width="358" alt="Screenshot 2022-08-28 at 09 36 22" src="https://user-images.githubusercontent.com/107396713/187056881-d03d3cdd-ef4e-4f2f-a449-f7847d845e2c.png">
Done
