### ISSUE TITLE
Additional Content to Threat Catalog

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#477]
We need to... 
- Transfer the documentation page from the current website
- Add a Menu to the Threat Catalog page. 
- Menu should include Catalog, Documentation, and Version History.

![image](https://user-images.githubusercontent.com/26025574/187082196-3096a714-a3a7-4583-a236-b2e3ccd97aa7.png)

**Comment by prabath-asrg** [comment]
Done. However on the previous site Documentation and Version history pages are incomplete. I have added them as they were. We may need to change these.
