### ISSUE TITLE
SOS Thank You Page

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#483]
We need another page to say thank you for the support.  Here is some text as introduction.  Please add some pictures, style and format. 

Planning events, particularly those presenting innovative and complex cybersecurity technologies, takes a village. As ASRG is a not-for-profit organization, we rely heavily on volunteers. Our volunteers range in skills from information security to business development to marketing. Most work full time in related cybersecurity or automotive companies. They are located around the world and serve in high responsibility positions. Yet, somehow over the last few months, they have found the time to contribute to the greater good of catalyzing assured cybersecurity for our impending extremely exposed and vulnerable smart mobility market. 
Therefore, this platform is to convey our deep appreciation for the hours of work invested in putting together Secure Our Streets 2022…

**Comment by prabath-asrg** [comment]
https://sos.asrg.io/thank-you-for-the-support/

**Comment by heldyboy** [comment]
@prabath-asrg Please make the following changes.
1. Change the title from "Companies" to "Directory"
2. Add Latest to the Sort where the newest entries will be sorted first. 
3. I think we want to remove the rating from the overview page.  Only for the Detail / Single Page. 
4. Change Check Profile to Details
5.

**Comment by heldyboy** [comment]
Here are the requested changes for the single pages... 
1. Logo should be limited to a size of 200x200 or something much smaller
2. We need to add some fields to the data structure. (Contact person name, Email, Linkedin)
3.

**Comment by heldyboy** [comment]
Opps looks like put this in the wrong ticket.  Can you please copy to the company directories ticket?

**Comment by heldyboy** [comment]
Regarding the Thank you page... I think we need to add a list at the bottom with all the people's names.

**Comment by prabath-asrg** [comment]
Sure will do

**Comment by prabath-asrg** [comment]
Added the names

https://sos.asrg.io/thank-you-for-the-support/
