### ISSUE TITLE
Event Page Changes

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#484]
Please make the following changes... 

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/26025574/187276783-f1c0ada6-2025-4be7-8e12-b6cfb9272276.png">

If the start date and end date is the same, then now end date is needed.  
Also, we can remove the To: and From:... it should be Start Date - End Date
Please make the address clickable, it either opens an external google maps link, or other map. 
Also, we should have an link to download the appointment for calendars (iCal, Outlook, etc.)

<img width="350" alt="image" src="https://user-images.githubusercontent.com/26025574/187277469-ca46ce5f-af12-4315-98eb-018229606ccf.png">
Please remove the Starts text... 
Please remove the "Duration:"
Please add the time zone information after the time. 
Please also remove the "Presenter:"

**Comment by usman-asrg** [comment]
Add to calender links are done  @prabath-asrg

**Comment by heldyboy** [comment]
Need to change the icons to symbols, or another easier way.

**Comment by usman-asrg** [comment]
Added the symbols 
![image](https://user-images.githubusercontent.com/96944860/195463184-e6a7146c-affc-48d3-956a-e2b0167983a4.png)
