### ISSUE TITLE
SOS: New Page for Presentations

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#487]
We should ahve a page with all the presentation titles, speakers, link to the videos, link to the presentation and so on for the SOS 2022 conference.  This page should be released on 16th of September.

**Comment by prabath-asrg** [comment]
@heldyboy Were can I find the schedule, speakers' names, presentations, and video links?

**Comment by heldyboy** [comment]
Hi Prabath, you can find it here...

https://secureourstreets.com

**Comment by heldyboy** [comment]
@prabath-asrg Can you please add the link?

**Comment by prabath-asrg** [comment]
Hey @heldyboy I can but still, we do not have uploaded the youtube links and presentation files. Is this okay?

**Comment by prabath-asrg** [comment]
https://sos.asrg.io/schedule-and-presentations/
