### ISSUE TITLE
Webinar and Event Forms

### ISSUE THREAD

**Issue by rinaespiritu01** [ASRG/asrg.io#493]
https://docs.google.com/document/d/1XCdhXsDNvC3CCRmBmv6VdyZLDDKWWmMmNvNEzuhwlzk/edit?usp=sharing

**Comment by prabath-asrg** [comment]
A new post type and a submit form are created. 

Submit Webinar Form: https://garage.asrg.io/webinar-submission/
Webinars: https://garage.asrg.io/webinars/
Single Page: https://garage.asrg.io/webinars/how-to-think-like-a-security-and-a-safety-manager/

**Comment by heldyboy** [comment]
@rinaespiritu01 Can you please review and give feedback?

**Comment by heldyboy** [comment]
Please add LinkedIn as optional.

**Comment by heldyboy** [comment]
The author should be able to edit and add information to the form in "My Webinars".

**Comment by heldyboy** [comment]
If someone clicks on the link to Terms and Conditions then a popup with the text will appear.

**Comment by heldyboy** [comment]
After submitting the form, the user will be forwarded to the best practices page.

**Comment by rinaespiritu01** [comment]
hey @heldyboy  the best practices page is at the bottom of this page https://garage.asrg.io/webinar-submission/

@prabath-asrg 

- can you move Submit Webinar to the bottom of the page so that they can see the best practices section?
- will the speakers be able to edit the content after they submit it?

**Comment by prabath-asrg** [comment]
Hi @rinaespiritu01,

- The best practices section is a new page now. Once the user submitted the webinar they will automatically redirect to the best practices page.
- Yes. Users can edit the webinar after submission. Then admins will receive an email and the webinar will be set to pending status.

**Comment by prabath-asrg** [comment]
My webinars: https://garage.asrg.io/account/my-webinars/
Webinar Submission: https://garage.asrg.io/webinar-submission/ (Please test the popup by clicking the Term of Submission right above the submit button)
Webinar Best Practices: https://garage.asrg.io/webinar-best-practices/

**Comment by heldyboy** [comment]
@rinaespiritu01 Can you take a look?

**Comment by rinaespiritu01** [comment]
@heldyboy @prabath-asrg just tried filling up the form - I was directed to the best practices after.

I also checked the submitted form on WordPress https://garage.asrg.io/wp-admin/post.php?post=7536&action=edit
@prabath-asrg  please check that page - how am I supposed to download the presentation file and headshot image?
<img width="542" alt="Screen Shot 2022-10-13 at 12 12 49 AM" src="https://user-images.githubusercontent.com/107185811/195352335-e1bbb570-5a5e-472f-ac33-b056de419067.png">

**Comment by rinaespiritu01** [comment]
@prabath-asrg  i see that there is a link generated to download the Presentation file in WP - https://garage.asrg.io/wp-content/uploads/jet-engine-forms/4166/2022/10/Presentation-Slides-Janos-Kovacs-Road-to-the-Roads.pdf

how about the headshot?

**Comment by prabath-asrg** [comment]
@rinaespiritu01 I have added these two files to the email notification. You can download them from there.

**Comment by rinaespiritu01** [comment]
thanks @prabath-asrg!   that works. thanks!
