### ISSUE TITLE
Disclosure updates

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#499]
1. Please fix the issues with the links. 
2. "Read Post" should be "More Information"
3. The images should fit... not stretch.  We should be able to see the entire logo in the box. 
4. Date is not needed 

![image](https://user-images.githubusercontent.com/26025574/193515442-d61d047b-fdd0-4e67-86f0-941687fe247e.png)

**Comment by prabath-asrg** [comment]
These are old posts for disclosure programs. Now we have a different setup. 

https://garage.asrg.io/disclosure-programs/
