### ISSUE TITLE
Add imprint

### ISSUE THREAD

**Issue by chrsengel** [ASRG/asrg.io#5]
Add imprint page with contact details.

**Comment by chrsengel** [comment]
I guess since asrg is not based in Germany we can close this @heldyboy?

**Comment by heldyboy** [comment]
We will create the e.V. on January 5th.  

Here is the generated code.  Can you add it please?

<h1>Legal Disclosure</h1>
Information in accordance with Section 5 TMG
<br><br>Stadtmitte<br>70193 Stuttgart<br>
<h2>Represented by</h2>
John Heldreth<br><br>
<h2>Contact Information</h2>
Telephone: +4917630661106<br>E-Mail: <a href="mailto:info@asrg.io">info@asrg.io</a><br>Internet address: <a href="www.asrg.io" target="_blank">www.asrg.io</a><br>
<h2>Register entry</h2>
Entry in: Vereinsregister<br>Register Number: 0000000<br>Register Court: None<br>
<h2>Graphics and Image Sources</h2>
CC0 1.0 Universal (CC0 1.0)<br />
Public Domain Dedication<br><br>
<h2>Disclaimer</h2>
Accountability for content<br>
The contents of our pages have been created with the utmost care. However, we cannot guarantee the contents'
accuracy, completeness or topicality. According to statutory provisions, we are furthermore responsible for 
our own content on these web pages. In this matter, please note that we are not obliged to monitor 
the transmitted or saved information of third parties, or investigate circumstances pointing to illegal activity. 
Our obligations to remove or block the use of information under generally applicable laws remain unaffected by this as per 
§§ 8 to 10 of the Telemedia Act (TMG).

<br><br>Accountability for links<br>
Responsibility for the content of 
external links (to web pages of third parties) lies solely with the operators of the linked pages. No violations were 
evident to us at the time of linking. Should any legal infringement become known to us, we will remove the respective 
link immediately.<br><br>Copyright<br> Our web pages and their contents are subject to German copyright law. Unless 
expressly permitted by law, every form of utilizing, reproducing or processing 
works subject to copyright protection on our web pages requires the prior consent of the respective owner of the rights. 
Individual reproductions of a work are only allowed for private use. 
The materials from these pages are copyrighted and any unauthorized use may violate copyright laws.

<br><br>
<i>Quelle: </i><a href="http://www.translate-24h.de" target="_blank">Deutsch-Englisch Übersetzungen</a> <br><br>
