### ISSUE TITLE
Need to add the job site to the Garage

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#502]

**Comment by prabath-asrg** [comment]
Ref: https://www.tesla.com/careers/search/

**Comment by prabath-asrg** [comment]
Need a list of job categories

**Comment by prabath-asrg** [comment]
Job Archive: https://garage.asrg.io/careers/
Job Single Page: https://garage.asrg.io/careers/controls-engineer-tesla-bot/

**Comment by heldyboy** [comment]
Update to look like rooster.jobs

**Comment by prabath-asrg** [comment]
@heldyboy please have a look

https://garage.asrg.io/careers/
