### ISSUE TITLE
Fix the Threat Catalog Width

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#507]

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/195378968-1ec8b09b-254e-4fb1-9e64-f30b2731e00f.png)

**Comment by prabath-asrg** [comment]
I have edited it. But When we edit the margins, it looks asymmetrical. Please have a look.

**Comment by heldyboy** [comment]
Please make the iFrame as wide as possible (with small border which looks good).  It will look asymmetrical, that's ok.  We need the space in the iFrame for the other menus. 

![image](https://user-images.githubusercontent.com/26025574/195500853-1ff66f74-a075-4c97-8903-5d6523377257.png)
