### ISSUE TITLE
User Profile Management: Implement page for profile management as outlined in plan. (i.e. /profile when clicking on avatar)

### ISSUE THREAD

**Issue by Melvin-Thomas-Dev** [ASRG/asrg.io#58]
will we be replacing the Django user model with a custom one and then link the profile to that? Or do we just create an additional profile model linked to the present one?

**Comment by brandonbarry123** [comment]
Today, the functionality is: user creates account, visits /profile, gets a page that says "fill out your profile". Once filled out, can access /profile. 

Then, user can "edit profile", which brings user back to /createprofile.

Data collected upon user registration is: User, email, password. 

Upon user creation, there needs to be a minimum dataset for ANY user:
1) First Name
2) Last Name
3) Occupational Status (i.e. student, professional, etc.)
4) Country

Optionally, a user can add information to their profile via /createprofile once an acct is created.
1) Gender
2) Date of birth
3) Field of Study
4) Bio
5) Status
6) Skills
7) Interests
8) Competencies
9) Profile Picture
10) Reset Password
