### ISSUE TITLE
Position Postings: Come out with basic table layout for position postings (ASRG-member view)

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#70]
Goal: come up with a basic area where members can view job opportunities. Something like:https://www.tesla.com/careers/search#/

We can start with a basic table (no need for search). Search would be a nice to have. We then need the ability to insert opportunities. 

To start, ASRG-admins can submit the job postings. In the future, we need ASRG members with the role of "Sponsor" to be able to publish job postings.

Consider using something that already exists, like: https://github.com/MicroPyramid/opensource-job-portal, https://djangopackages.org/grids/g/jobboards/

**Comment by peterbogdan** [comment]
Created a job posting models with the following fields: 
```
    title = models.CharField(max_length=80)
    job_category = models.CharField(max_length=120)
    location = models.CharField(max_length=56, null=False, blank=False)
    date_posted = models.DateTimeField(blank=True, auto_now_add=True)
    job_description = models.TextField(blank=True)

```

If you would like more fields let me know and I will add them, also added filters for job_category, location, and date_posted.
Created a basic view of the postings with datatable and filters and will update with the details page
