### ISSUE TITLE
Events Page: Design and Develop a page that stores information about upcoming ASRG events.

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#73]
Events page needs to pull information from the ASRG events roadmap to display upcoming events to the end user. For example, the next webinar, workshop, etc. 

In future, events will be exclusively stored and managed through member portal.

**Comment by brandonbarry123** [comment]
The events page will simply show a user a list of published events with data similar to https://asrg.io/world/webinars.html. I.e.
*Event Title
*Event Presenter
*Event Description
*Event Time/date
*Link to Youtube LiveStream

A table of all events stored in the database will be displayed at /events.

At /admin, an administrator can "create/publish" a new event with the above mentioned fields.

**Comment by brandonbarry123** [comment]
https://docs.google.com/spreadsheets/d/1ifxOT5_Vca_MItTDWKPD_nuB9cGyPrevgPbat-BFXrQ/edit?usp=sharing

**Comment by heldyboy** [comment]
Here are some of the fields (from my point of view) that we need to have in the events dB...

Event Type
Range: Webinar, Meeting, CTF, Workshop, Conference, Tournament
Range Constraints:  Only the defined selections.
Definition:
Webinar - Online presentation (this will need a link to the event)
Meeting - This will be a face to face meeting (This will need an address and other location information)
CTF - Capture the Flag event.  (This will need a link and location information)
Workshop - This will be a face to face workshop but will need a register link as well probably.  (This will need a link field and location information)
Conference - This will be all security, automotive, hacking, etc. conferences.  (This will need a link field and location field)
Tournament - This will be for tournaments. (This will need a link field and location field)

Status
Range: 1 - In Plan, 2 - Confirmed, 3 - Invited, 4 - Completed, 5 - Cancelled
Definition:  Status of the event.

ASRGorg
Range: Internal / External
Definitions:
Internal: ASRG organized event.
External: Event which is not organized by ASRG.  This will have all the BSides / Defcons / etc.

ASRGlocation
Range:  All the ASRG locations.
This defines which location is hosting the event. 
Needed only for ASRGorg:Internal events.

Host
Range: All ASRG Leaders and Organizers
Definition: Who is responsible as host for the event. 
Needed only for ASRGorg:Internal events.

Title
Range: Free Text 
Range Constraints: If ASRGorg:Internal event then less then 80 Characters (limitation of Meetup)
Definition: Title of the event.

Presenter First Name
Range: Free Text
Range Constraints: none
Definition: First name of Presenter.

Presenter Last Name
Range: Free Text
Range Constraints: none
Definition: Last name of Presenter.

Presenter Picture
Range: File
Range Constraints: JPG, GIF, PNG, TIFF... image formats
Definition: Picture of the presenter.  This will be used for the marketing material.

Presenter Company Name
Range: Free Text
Range Constraints: none
Definition: Company of Presenter

Presenter Company Logo
Range: File
Range Constraints: JPG, GIF, PNG, TIFF... image formats
Definition: Logo of presenters company.  This will be used for the marketing material.

Presenter Bio
Range: Free Text
Definition: This will be the short biography of the presenter. 

Event Address
Range: Internation Address field (start with Country) then the country will appear the rest of the fields to enter the correct address format.  Start with India, Romania, and US.  If you have questions how the address should look like in those countries, please ask the colleagues. 
Definition: The address of where the event will take place.

Event Start Date
Range: Date Format
Definition:  This will be the start date of the event. 

Event Start Time
Range: Time and Time Zone
Definition: This will be the start time of the event.

Event End Date
Range: Date Format
Definition: This will be the end date of the event.

Event End Time
Range: Time and Time Zone
Definition: This will be the end time of the event.

Event Description
Range: Free Text
Definition:  This will be the abstract or description of the event. 

What else am I forgetting???

**Comment by Melvin-Thomas-Dev** [comment]
I have added all the fields @heldyboy mentioned.
Additionally, I have added the following fields too

1. Presenter company website
2. presenter social profile link
3. Presenter designation

I forgot about the timezone. I am working on that and hopefully will be able to push it before the meeting today.

**Comment by brandonbarry123** [comment]
Embed 'events' page separately in the member portal (i.e. same client code, just embedded inside of the member portal instead of redirecting to public events page). The point of this is to keep the user inside of the member portal.
