### ISSUE TITLE
Main Dashboard: implement basic main dashboard view as agreed upon in layout. (i.e. /dashboard, navigated to immediately when logging in or when clicking ASRG logo in top left)

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#74]
Goal: Main dashboard should summarize critical information across the member portal. Because we are just starting to develop the member portal, we will keep the main dashboard simple to start.

Main dashboard will include more information in the future. For now, we will keep this extremely basic:

1) Announcements (if possible, allow announcements through /admin).
2) Upcoming Events (reference meetup for upcoming webinars?)
3) Embed a basic map geolocation all of our chapters. 
4) 3 core cards: Knowledge, Networking, Collaboration. 
- Knowledge (TBD)
- Networking (Join Slack Link, Join Telegram Link, Join Whatsapp link, etc.)
- Collaboration (TBD)

**Comment by heldyboy** [comment]
![image](https://user-images.githubusercontent.com/26025574/91337096-2b5f4100-e7d3-11ea-86ef-804e856a7549.png)

**Comment by brandonbarry123** [comment]
Some parts of this are implemented. Need to find a library where pins and information can be stored on the map.

**Comment by brandonbarry123** [comment]
@peterbogdan is going to look for a library that facilitates this.
