### ISSUE TITLE
Add dynamically updated fields to landing page.

### ISSUE THREAD

**Issue by brandonbarry123** [ASRG/asrg.io#75]
Statistics should be updated in real time based on data stored/updated in the /admin portal or config file. This allows ASRG admins (like John) to update key stats on the landing page quickly. 

In the future, this will be dynamically connected to the member database to provide real-time numbers.

**Comment by peterbogdan** [comment]
Added in 
https://github.com/ASRG/asrg.io/pull/100

**Comment by brandonbarry123** [comment]
@mikeyhuntington What is the date of founding of the ASRG? @peterbogdan can adjust the field to update automatically based on the different between date.today and date of founding.

**Comment by brandonbarry123** [comment]
@mikeyhuntington also, what do we want to put for "members" and "meetings"? Right now, Peter has it set up to reflect number of user accounts in the database. However, this will make our membership look very low until we get people creating member accounts. 

For members, I suggest we hard code something for now. In future, we can fall back onto member portal member count. 

For meetings, I'm not sure. Maybe we delete? Otherwise, it could be the sum of all events in "/events". If we put all past events into the member portal, then it will be an accurate count.

**Comment by brandonbarry123** [comment]
Events should be a sum of all events in /events.
