### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#76]
When you register, and it is successful, then the fields to enter information should no longer be shown.  

When you register and the user is already existing, the current message is "Form is not valid".  The message should be "Already Existing, please create new registration or reset your password." IN RED.

**Comment by Melvin-Thomas-Dev** [comment]
I will get it done @heldyboy

**Comment by heldyboy** [comment]
Thanks sir!

**Comment by Melvin-Thomas-Dev** [comment]
Hey, 
I just pushed the modifications you suggested.
I am closing the issue.
If you need more changes feel free to reopen the issue again.
