### ISSUE TITLE
Chapters and Groups

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#87]
It seems that we have two places where the chapters / locations are defined.  We should have one model that defines the locations and then reference that model in the other apps. 

![image](https://user-images.githubusercontent.com/26025574/94513014-e7ba8580-021d-11eb-8f35-035b4d92b0e3.png)

**Comment by Melvin-Thomas-Dev** [comment]
The "Groups" is created by Django. It is used to create a group for a set of people and then assigns specific permissions to the groups.
This is how I understand it.

Say like we can have a group that is L1_Sponsors and then adds permissions for L1_Sponsors to that group. So every time we have a new L1_sponsor we just have to add the new sponsor to that group and all the permissions of an L1_Sponsor will be added to that account.
That is why we need "Groups". The Chapters are only created in one place
