### ISSUE TITLE
/register: Remove "We just need a little more info about you..."

### ISSUE THREAD

**Issue by Melvin-Thomas-Dev** [ASRG/asrg.io#95]
Remove "Gender"

For occupational status: change selections to match "Job Titles" at https://hardwear.io/netherlands-2020/register.php

Remove "Add your credentials OR use an ASRG account" (it already saves "Have an account? Login" at the bottom)

**Comment by Melvin-Thomas-Dev** [comment]
I looked into the hardwear.io website and couldn't find "Job Titles". Probably because the registrations for the conference has closed. Could you please post the details of the choices that are needed? @brandonbarry123

**Comment by brandonbarry123** [comment]
Need to discuss what else to display here. I.e. we should have fields such as "hobby car hacker", things that are relevant in the space @mikeyhuntington.
